[package]
name = "hw14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.4"
ark-ff = "0.4"
ark-std = { version = "0.4", features = ["getrandom"] }
